### ISSUE TITLE
Does not work in Vulkan 1.2

### ISSUE THREAD

**Issue by kapkic** [Lephar/Engine#1]
I've been an avid user of your engine, thank you a lot for providing this.
But with the latest updates to Vulkan (namely 1.2), I've been having problems running the code.

I think it might be because of the "VK_LAYER_LUNARG_standard_validation" code in line 156. Since it's a deprecated method, it might be better to use VK_LAYER_KHRONOS_validation.

Please update this ASAP. Thank you.

**Comment by Lephar** [comment]
Thanks for your interest, fixed with 75776f421fc42657e518ad15aeca01494d189587.
